/**
 * FairShare – Chore Preset Definitions
 * 50 pre-defined chores grouped by category.
 * Used during onboarding to seed a household's chore catalog.
 */

export type ChoreCategory = 'cleaning' | 'cooking' | 'laundry' | 'invisible' | 'care' | 'etc';

export interface ChorePreset {
  title: string;
  titleEn: string;
  icon: string;
  category: ChoreCategory;
  points: number;
  requiresPhoto: boolean;
  requiresApproval: boolean;
  isInvisibleLabor: boolean;
  estimatedMinutes: number;
  modes: Array<'couple' | 'family' | 'roommate'>;
}

export const CHORE_PRESETS: ChorePreset[] = [
  // ── 청소 (Cleaning) ──────────────────────────────────────
  {
    title: '거실 청소',
    titleEn: 'Living Room Cleaning',
    icon: '🛋️',
    category: 'cleaning',
    points: 3,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 20,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '화장실 청소',
    titleEn: 'Bathroom Cleaning',
    icon: '🚽',
    category: 'cleaning',
    points: 5,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 30,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '방 청소',
    titleEn: 'Room Cleaning',
    icon: '🛏️',
    category: 'cleaning',
    points: 3,
    requiresPhoto: true,
    requiresApproval: true,
    isInvisibleLabor: false,
    estimatedMinutes: 20,
    modes: ['family'],
  },
  {
    title: '창문 닦기',
    titleEn: 'Window Cleaning',
    icon: '🪟',
    category: 'cleaning',
    points: 4,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 25,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '청소기 돌리기',
    titleEn: 'Vacuuming',
    icon: '🧹',
    category: 'cleaning',
    points: 3,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 15,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '걸레질',
    titleEn: 'Mopping',
    icon: '🧽',
    category: 'cleaning',
    points: 2,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 15,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '쓰레기 분리수거',
    titleEn: 'Recycling',
    icon: '♻️',
    category: 'cleaning',
    points: 3,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 10,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '쓰레기 버리기',
    titleEn: 'Taking out Trash',
    icon: '🗑️',
    category: 'cleaning',
    points: 2,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 5,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '욕실 정리',
    titleEn: 'Bathroom Tidying',
    icon: '🛁',
    category: 'cleaning',
    points: 2,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 10,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '현관 청소',
    titleEn: 'Entryway Cleaning',
    icon: '🚪',
    category: 'cleaning',
    points: 2,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 10,
    modes: ['couple', 'family', 'roommate'],
  },

  // ── 요리 (Cooking) ──────────────────────────────────────
  {
    title: '밥 짓기',
    titleEn: 'Making Rice',
    icon: '🍚',
    category: 'cooking',
    points: 2,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 30,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '아침 준비',
    titleEn: 'Preparing Breakfast',
    icon: '🌅',
    category: 'cooking',
    points: 5,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 20,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '저녁 준비',
    titleEn: 'Preparing Dinner',
    icon: '🍳',
    category: 'cooking',
    points: 7,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 45,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '설거지',
    titleEn: 'Doing Dishes',
    icon: '🍽️',
    category: 'cooking',
    points: 3,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 15,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '식기세척기 정리',
    titleEn: 'Unloading Dishwasher',
    icon: '🫙',
    category: 'cooking',
    points: 2,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 10,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '장보기',
    titleEn: 'Grocery Shopping',
    icon: '🛒',
    category: 'cooking',
    points: 5,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 60,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '냉장고 정리',
    titleEn: 'Fridge Organization',
    icon: '🧊',
    category: 'cooking',
    points: 3,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 20,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '간식 준비',
    titleEn: 'Preparing Snacks',
    icon: '🍎',
    category: 'cooking',
    points: 2,
    requiresPhoto: true,
    requiresApproval: true,
    isInvisibleLabor: false,
    estimatedMinutes: 10,
    modes: ['family'],
  },

  // ── 세탁 (Laundry) ──────────────────────────────────────
  {
    title: '세탁기 돌리기',
    titleEn: 'Running Laundry',
    icon: '🫧',
    category: 'laundry',
    points: 2,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 10,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '빨래 널기',
    titleEn: 'Hanging Laundry',
    icon: '👕',
    category: 'laundry',
    points: 3,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 15,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '빨래 개기',
    titleEn: 'Folding Laundry',
    icon: '🧺',
    category: 'laundry',
    points: 3,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 20,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '옷 정리',
    titleEn: 'Organizing Clothes',
    icon: '👔',
    category: 'laundry',
    points: 2,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 10,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '침구 세탁',
    titleEn: 'Washing Bedding',
    icon: '🛌',
    category: 'laundry',
    points: 5,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 20,
    modes: ['couple', 'family', 'roommate'],
  },

  // ── 돌봄 (Care) ──────────────────────────────────────
  {
    title: '반려동물 밥주기',
    titleEn: 'Feeding Pets',
    icon: '🐾',
    category: 'care',
    points: 2,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 10,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '반려동물 산책',
    titleEn: 'Walking Pets',
    icon: '🦮',
    category: 'care',
    points: 5,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 30,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '아이 목욕시키기',
    titleEn: 'Bathing Child',
    icon: '🧸',
    category: 'care',
    points: 5,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 30,
    modes: ['family'],
  },
  {
    title: '아이 숙제 도와주기',
    titleEn: 'Helping with Homework',
    icon: '📚',
    category: 'care',
    points: 4,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 30,
    modes: ['family'],
  },
  {
    title: '아이 등하원',
    titleEn: 'School Drop-off/Pick-up',
    icon: '🚌',
    category: 'care',
    points: 4,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 30,
    modes: ['family'],
  },
  {
    title: '노인 돌봄',
    titleEn: 'Elderly Care',
    icon: '👴',
    category: 'care',
    points: 6,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 60,
    modes: ['family'],
  },

  // ── 정신노동 (Invisible Labor) ──────────────────────────────────────
  {
    title: '병원 예약',
    titleEn: 'Medical Appointment Booking',
    icon: '🏥',
    category: 'invisible',
    points: 5,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: true,
    estimatedMinutes: 20,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '공과금 납부',
    titleEn: 'Paying Utilities',
    icon: '📋',
    category: 'invisible',
    points: 4,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: true,
    estimatedMinutes: 15,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '준비물 챙기기',
    titleEn: 'Preparing Supplies',
    icon: '🎒',
    category: 'invisible',
    points: 3,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: true,
    estimatedMinutes: 15,
    modes: ['family'],
  },
  {
    title: '집 수리 예약',
    titleEn: 'Home Repair Scheduling',
    icon: '🔧',
    category: 'invisible',
    points: 5,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: true,
    estimatedMinutes: 20,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '가족 일정 관리',
    titleEn: 'Managing Family Schedule',
    icon: '📅',
    category: 'invisible',
    points: 4,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: true,
    estimatedMinutes: 20,
    modes: ['couple', 'family'],
  },
  {
    title: '선물 구매',
    titleEn: 'Gift Purchasing',
    icon: '🎁',
    category: 'invisible',
    points: 4,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: true,
    estimatedMinutes: 30,
    modes: ['couple', 'family'],
  },
  {
    title: '보험 관리',
    titleEn: 'Insurance Management',
    icon: '📄',
    category: 'invisible',
    points: 5,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: true,
    estimatedMinutes: 30,
    modes: ['couple', 'family'],
  },
  {
    title: '식단 계획',
    titleEn: 'Meal Planning',
    icon: '📝',
    category: 'invisible',
    points: 3,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: true,
    estimatedMinutes: 20,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '집 물건 재고 확인',
    titleEn: 'Home Inventory Check',
    icon: '🔍',
    category: 'invisible',
    points: 2,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: true,
    estimatedMinutes: 15,
    modes: ['couple', 'family', 'roommate'],
  },

  // ── 기타 (Etc) ──────────────────────────────────────
  {
    title: '물 갈아주기',
    titleEn: 'Watering Plants',
    icon: '🪴',
    category: 'etc',
    points: 1,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 5,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '우편물 확인',
    titleEn: 'Checking Mail',
    icon: '📬',
    category: 'etc',
    points: 1,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 5,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '택배 수령',
    titleEn: 'Receiving Packages',
    icon: '📦',
    category: 'etc',
    points: 1,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 5,
    modes: ['couple', 'family', 'roommate'],
  },
  {
    title: '자동차 관리',
    titleEn: 'Car Maintenance',
    icon: '🚗',
    category: 'etc',
    points: 5,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 60,
    modes: ['couple', 'family'],
  },
  {
    title: '이웃 인사',
    titleEn: 'Greeting Neighbors',
    icon: '👋',
    category: 'etc',
    points: 1,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 5,
    modes: ['family', 'roommate'],
  },
  {
    title: '공용 공간 정리',
    titleEn: 'Shared Space Tidying',
    icon: '🏠',
    category: 'etc',
    points: 3,
    requiresPhoto: false,
    requiresApproval: false,
    isInvisibleLabor: false,
    estimatedMinutes: 20,
    modes: ['roommate'],
  },
  {
    title: '책상 정리',
    titleEn: 'Desk Organizing',
    icon: '🖥️',
    category: 'etc',
    points: 2,
    requiresPhoto: true,
    requiresApproval: true,
    isInvisibleLabor: false,
    estimatedMinutes: 10,
    modes: ['family'],
  },
];

export const PRESET_BY_CATEGORY = CHORE_PRESETS.reduce<Record<ChoreCategory, ChorePreset[]>>(
  (acc, preset) => {
    if (!acc[preset.category]) {
      acc[preset.category] = [];
    }
    acc[preset.category].push(preset);
    return acc;
  },
  {} as Record<ChoreCategory, ChorePreset[]>
);

export const CATEGORY_LABELS: Record<ChoreCategory, string> = {
  cleaning: '청소',
  cooking: '요리',
  laundry: '세탁',
  invisible: '정신노동',
  care: '돌봄',
  etc: '기타',
};
